"""initial migration

Revision ID: a12f3724b454
Revises: 2d3be2c2aafa
Create Date: 2016-05-23 00:24:43.766000

"""

# revision identifiers, used by Alembic.
revision = 'a12f3724b454'
down_revision = '2d3be2c2aafa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
